version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "CHANGES.rst" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - /home/circleci/.local/share/virtualenvs/
          key: v1-dependencies-{{ checksum "CHANGES.rst" }}

      - run:
          name: linters
          command: |
            . venv/bin/activate
            SKIP=no-commit-to-branch pre-commit run -a -v

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test -vv -s --cov hulks --cov-report=term-missing --cov-report=html

      - store_artifacts:
          path: htmlcov
          destination: test-reports

branches:
  only:
    - master
